/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HP63gFiPFgo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Chivo } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from '@/components/ui/button'
import Image from 'next/image'
import Link from 'next/link'

export function Hero() {
    return (
        <section className='w-full pt-12 md:pt-24 lg:pt-32'>
            <div className='container space-y-10 xl:space-y-16'>
                <div className='grid gap-4 px-10 md:grid-cols-2 md:gap-16'>
                    <div>
                        <h1 className='lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]'>
                            Visualizá los problemas ambientales más comunes
                        </h1>
                    </div>
                    <div className='flex flex-col items-start space-y-4'>
                        <p className='mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400'>
                            Nuestra página muestra y registra los incidentes ambientales
                            en Argentina a través de nuestro mapa interactivo.
                        </p>
                        <div className='flex flex-col gap-2 min-[400px]:flex-row'>
                            <Button asChild>
                                <Link href='#'>Ver mapa</Link>
                            </Button>
                        </div>
                    </div>
                </div>
                <Image
                    alt='Hero'
                    className='mx-auto aspect-[3/1] overflow-hidden rounded-t-xl object-cover'
                    height='300'
                    src='/placeholder.svg'
                    width='1270'
                />
            </div>
        </section>
    )
}
