/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3ARyWr5xt9J
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

export function RegisterForm() {
    return (
        <form className='grid gap-4'>
            <div className='grid gap-2'>
                <Label htmlFor='email'>Email</Label>
                <Input
                    id='email'
                    placeholder='ejemplo@greenalert.com'
                    required
                    type='email'
                />
            </div>
            <div className='grid gap-2'>
                <Label htmlFor='password'>Contraseña</Label>
                <Input
                    id='password'
                    placeholder='••••••••'
                    required
                    minLength={6}
                    type='password'
                />
            </div>
            <Button
                className='w-full'
                type='submit'
            >
                Registrarme
            </Button>
        </form>
    )
}
